### ISSUE TITLE
Botó d'enviar

### ISSUE THREAD

**Issue by jaumeortola** [Softcatala/separador-sillabes#4]
Si el text que s'escriu és llarg (per exemple un poema sencer), fer tots els càlculs cada vegada que s'alça una tecla (onkeyup) és costós i pot acabar molestant l'entrada de lletres (pot arribar a perdre's alguna tecla picada). La solució seria posar un botó d'enviar.

**Comment by pereorga** [comment]
Per resoldre el problema d'executar càlculs durant esdeveniments que es poden executar moltes vegades (en aquest cas només es vol que s'executi l'última, i mai que s'executin dues vegades alhora), John Resig va proposar una manera que pot anar bé: https://johnresig.com/blog/learning-from-twitter/ (el post, de 2011, és interessant, però només cal llegir el codi de la part del final).

Jo em vaig trobar amb un problema semblant i vaig preferir resoldre-ho sense cap esdeveniment, comprovant si el text canviava cada 1 segon, i executant el que volia fer només en el cas que el text canviava: https://github.com/pereorga/minimalist-web-notepad/blob/master/script.js

Pel que fa a l'esdeveniment 'onkeyup', probablement 'oninput' és una millor elecció per detectar canvis (detecta també quan s'enganxa text amb el ratolí o amb el mòbil): https://stackoverflow.com/a/14029861/1391963

Puc fer una PR amb el que estic dient, tot i que això no resoldrà el problema del rendiment amb textos llargs si un usuari es posa a escriure. Per aquests casos (rars?) l'opció del botó no és dolenta.

**Comment by jaumeortola** [comment]
Gràcies, @pereorga. 
M'ha vingut al cap una altra possibilitat que es pot provar: fer _cache_ de les separacions per línia. De fet, la funció que fa la divisió sil·làbica ja fa _cache_ de les paraules dividides, o sigui que el gros de les operacions ja no es repeteix.

**Comment by jaumeortola** [comment]
Anoto que el canvi en la resposta es nota en passar d'una línia a dues línies. Escrivint en una línia sola no hi ha cap problema, i quan n'hi ha més d'una es nota molt, fins i tot posant-hi una cache. No ho entenc.

**Comment by jaumeortola** [comment]
Canviant "onkeyup" per "oninput" desapareixen els problemes.
